server:
  port: 9007 #Tomcat \u7AEF\u53E3\u53F7
  tomcat:
    uri-encoding: UTF-8 #\u8BBE\u7F6E\u670D\u52A1\u5668\u5B57\u7B26\u96C6

spring:
  application:
    name: tensquare-search #\u6A21\u5757\u540D\u5B57
  http: #HTTP\u8BF7\u6C42
    encoding:
      charset: UTF-8 #\u6240\u6709\u5B57\u7B26\u96C6UTF-8
      force: true
      enabled: true
  data:
    elasticsearch:
      cluster-nodes: 192.168.28.130:9300