server:
  port: 12000
spring:
  application:
    name: tensquare-config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/wodejiawang/tensquare_parent.git
  rabbitmq:
    host: 192.168.28.130
management: #暴露总线地址
  endpoints:
    web:
      exposure:
        include: bus-refresh
