server:
  port: 9012
spring:
  application:
    name: tensquare-web
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer-ip-address: true
zuul:
  routes:
    tensquare-base:   #基础
      path: /base/**  #请求规则
      serviceId: tensquare-base #指定Eureka注册中心中的服务的编号
    tensquare-user:   #基础
      path: /user/**  #请求规则
      serviceId: tensquare-user #指定Eureka注册中心中的服务的编号
    tensquare-qa:   #基础
      path: /qa/**  #请求规则
      serviceId: tensquare-qa #指定Eureka注册中心中的服务的编号
    tensquare-article:
      path: /article/**  #请求规则
      serviceId: tensquare-article #指定Eureka注册中心中的服务的编号
    tensquare-friend:
      path: /friend/**
      serviceId: tensquare-friend
    tensquare-gathering:
      path: /gathering/**
      serviceId: tensquare-gathering
    tensqure-recruit:
      path: /recruit/**
      serviceId: tensqure-recruit
    tensqure-search:
      path: /search/**
      serviceId: tensqure-search
    tensquare-spit:
      path: /spit/**
      serviceId: tensquare-spit
