server:
  port: 9005 #Tomcat 端口号
  tomcat:
    uri-encoding: UTF-8 #设置服务器字符集

spring:
  application:
    name: tensquare-gathering #模块名字
  datasource: #数据源的配置
    driverClassName: com.mysql.jdbc.Driver #数据库驱动
    url: jdbc:mysql://192.168.28.130:3306/tensquare_gathering?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root #账户名
    password: 123456 #密码
  jpa:    #SpringData Jpa的配置
    database: MySQL #数据库MYSQL
    show-sql: true  #显示SQL语句在控制台
    open-in-view: false  #禁用视图
  http: #HTTP请求
    encoding:
      charset: UTF-8 #所有字符集UTF-8
      force: true
      enabled: true